//All form element selectors are defined here

export class FormPageElement {
    selectPreferredFacility = '.max-w-3xl > :nth-child(1) > .flex';
    selectFaciliyName = '.max-w-3xl > :nth-child(1) > .font-medium';
    selectHousingCategory = '.max-w-3xl > .flex-col > :nth-child(1) > .flex';
    selectLivingOption = '.max-w-3xl > .flex-col > :nth-child(2) > .flex';
    fullNames = '#fullNames';
    lastName = '#lastName';
    dateOfBirth = ':nth-child(1) > .inline-flex';
    idNumberType = '.sm\:flex-row > :nth-child(1) > .flex';
    idNumber = '#saId';
    emailAddress = '#email';
    phoneNumberOwn = '#phoneOwn';
    typeOfApplication = '.space-y-10 > :nth-child(2) > :nth-child(4) > :nth-child(1)';
    applicationNew = '[aria-labelledby*="radix-"]';
    applicationRenewal = '[aria-labelledby*="radix-"]';
    phoneNumberClild = '#phoneChild';
    address = '#address';
    postalCode = '#areaCode';
    genderMale = '#gender-male';
    genderFemale = '#gender-female' ;
    gender = '.space-y-10 > :nth-child(3) > :nth-child(1) > :nth-child(1)';
    raceColored = '#race-colored';
    raceIndian = '#race-indian';
    raceBlack = '#race-black';
    raceWhite = '#race-white';
    maritalMarried = '#marital-married';
    maritalSingle = '#marital-single';
    maritalDivorced = '#marital-divorced';
    maritalWidowed = '#marital-widowed';
    maritalSeparated = '#marital-separated';
    maritalOtherPrefernottosay = '#marital-OtherPrefernottosay';
    homeLanguage = '#homeLanguage';
    religion = '#churchInvolvement';
    occupation = '#currentWork';
    name = '#funeralPersonName';
    phoneNumber = '#funeralPersonPhone';
    referenceNumber = '#funeralReferenceNo';
    address1 = '#funeralAddress';
    hospitalName = '#hospitalName';
    fileNumber = '#hospitalFileNo';
    nameOfMedicalFund = '#medicalFundName';
    nameOfPlan = '#medicalPlanName';
    medicalAidNumber = '#medicalAidNumber';
    doctorName = '#doctorName';
    doctorPhoneNo = '#doctorPhone'; 
    childFullName = '#children.0.fullName';
    childPhoneNo = '#children.0.phoneNo';  
    childCellNo = '#children.0.cellNO';   
    childEmail = '#children.0.email';
    childAddress = '#children.0.address';
    childRelationship = '#children.0.relationship';
    childOccupation = '#children.0.occupation';
    addMoreChildrenBtn = ':nth-child(4) > .inline-flex';
    healthStatusTextarea = '#healthStatus';  
    medicalDiagnosisTextarea = '#medicalDiagnosis';  
    allergiesInput = '#allergies';
    mobilityCheckbox = ':nth-child(1) > .space-x-2 > .peer';
    bathingCheckbox = '.space-y-4 > :nth-child(2) > .items-center > .peer';
    mobilityDescribe = '#mobilityDescribe'; 
    bathingDescribe = '#bathingDescribe';   
    canDoItMyselfCheckbox = '#finance-myself';
    needHelpCheckbox = '#finance-help ';
    someoneManagesCheckbox = '#finance-managed';
    immediatelyCheckbox = '#intake-immediately';
    within3MonthsCheckbox = '#intake-3months';
    within6MonthsCheckbox = '#intake-6months';
    laterCheckbox = '#intake-later';

}
